export const randomImage = () => {
  return `/imgs/${Math.floor(Math.random() * 6) + 1}.jpg`;
};

export const blog_categories = [
  // "All",
  "Technology",
  "Business",
  "Health",
  "Entertainment",
  "Science",
  "Sports",
  "Education",
  "Lifestyle",
  "Politics",
  "Fashion",
  "Travel",
  "Food",
  "Music",
  // "Art",
  // "Environment",
  // "Film",
  // "Books",
  // "History",
  // "Religion",
  // "Culture",
  // "Economy",
  // "Society",
  // "Psychology",
  // "Philosophy",
  // "Language",
  // "Architecture",
  // "Design",
  // "Photography",
  // "Craft",
  // "DIY",
  // "Parenting",
  // "Relationship",
  // "Beauty",
  // "Fitness",
  // "Nutrition",
];
